"""PostgreSQL 저장소: 관리 설정, 수신 상태와 영속 메일 큐."""
from contextlib import contextmanager
from dataclasses import replace
from datetime import datetime, timezone
import os
import time

import psycopg
from psycopg.rows import dict_row

from .message import HeartbeatMessage
from .storage import StoredDeviceState, NotificationJob, _StoredKafkaRecord


SCHEMA = """
CREATE TABLE IF NOT EXISTS devices (
    device_id TEXT PRIMARY KEY,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    reason TEXT NOT NULL DEFAULT '',
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS device_states (
    device_id TEXT PRIMARY KEY REFERENCES devices(device_id),
    raw_payload TEXT NOT NULL,
    kafka_key TEXT,
    kafka_topic TEXT NOT NULL,
    kafka_partition INTEGER NOT NULL,
    kafka_offset BIGINT NOT NULL,
    last_seen_at DOUBLE PRECISION NOT NULL,
    stale_notified BOOLEAN NOT NULL DEFAULT FALSE,
    status_alert_notified BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE TABLE IF NOT EXISTS notification_queue (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dedupe_key TEXT NOT NULL,
    device_id TEXT NOT NULL REFERENCES devices(device_id),
    notification_type TEXT NOT NULL,
    detail TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'PENDING',
    attempt_count INTEGER NOT NULL DEFAULT 0,
    next_attempt_at DOUBLE PRECISION NOT NULL,
    raw_payload TEXT NOT NULL,
    kafka_key TEXT,
    kafka_topic TEXT NOT NULL,
    kafka_partition INTEGER NOT NULL,
    kafka_offset BIGINT NOT NULL,
    last_error TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    sent_at TIMESTAMPTZ
);
CREATE UNIQUE INDEX IF NOT EXISTS notification_active_dedupe
 ON notification_queue(dedupe_key) WHERE status IN ('PENDING','RETRY','SENDING');
CREATE INDEX IF NOT EXISTS notification_due
 ON notification_queue(status, next_attempt_at, id);
"""


class PostgresRepository:
    """thread/요청별 저장소. 같은 인스턴스를 여러 thread에서 공유하지 않는다."""

    def __init__(self, dsn: str):
        """입력: PostgreSQL DSN. 반환: 저장소 객체. 이 시점에는 접속하지 않는다."""
        self.dsn = dsn
        self._current = None

    def connect(self):
        """입력: 없음. 반환: timeout과 dict 행 형식이 설정된 새 DB 연결."""
        return psycopg.connect(self.dsn, connect_timeout=5, row_factory=dict_row,
                               options='-c statement_timeout=45000 -c lock_timeout=35000')

    @contextmanager
    def transaction(self):
        """입력: 없음. 반환: 작업 단위 연결. 상태와 큐를 함께 commit/rollback한다."""
        if self._current is not None:
            yield self._current
            return
        with self.connect() as conn:
            self._current = conn
            try:
                yield conn
            finally:
                self._current = None

    def initialize(self):
        """입력: 없음. 반환: 없음. 초기 스키마 생성을 직렬화하며 기존 데이터는 보존한다."""
        with self.transaction() as conn:
            conn.execute('SELECT pg_advisory_xact_lock(819271)')
            conn.execute(SCHEMA)

    def recover_jobs(self):
        """입력: 없음. 반환: 없음. 단일 consumer 시작 시 중단된 발송 작업을 복구한다."""
        with self.transaction() as conn:
            conn.execute("UPDATE notification_queue SET status='RETRY', next_attempt_at=%s "
                         "WHERE status='SENDING'", (time.time(),))

    def lock_management(self, device_id):
        """입력: 장비 ID. 반환: 없음. 관리 변경과 SMTP만 직렬화하고 소비는 막지 않는다."""
        if self._current is None:
            raise RuntimeError('lock_management requires a transaction')
        self._current.execute('SELECT pg_advisory_xact_lock(hashtextextended(%s, 819272))',
                              (device_id,))

    def monitoring_allowed(self, device_id):
        """입력: 장비 ID. 반환: 감시 허용 여부. 삭제/제외 설정을 heartbeat로 덮어쓰지 않는다."""
        with self.transaction() as conn:
            conn.execute('INSERT INTO devices(device_id) VALUES (%s) ON CONFLICT DO NOTHING',
                         (device_id,))
            row = conn.execute('SELECT enabled,deleted FROM devices WHERE device_id=%s FOR UPDATE',
                               (device_id,)).fetchone()
            return row['enabled'] and not row['deleted']

    def load_all(self):
        """입력: 없음. 반환: 삭제되지 않은 수신 상태 목록. 관리 변경과 상태 갱신을 직렬화한다."""
        with self.transaction() as conn:
            rows = conn.execute('SELECT s.* FROM devices d JOIN device_states s USING(device_id) '
                                'WHERE NOT d.deleted ORDER BY d.device_id FOR UPDATE OF d').fetchall()
            states = []
            for row in rows:
                heartbeat = replace(HeartbeatMessage.from_kafka_record(_StoredKafkaRecord(row)),
                                    consumed_at=datetime.fromtimestamp(row['last_seen_at'], timezone.utc))
                states.append(StoredDeviceState(
                    heartbeat=heartbeat, last_seen_at=row['last_seen_at'],
                    status_signature=heartbeat.status_signature(),
                    stale_notified=row['stale_notified'],
                    status_alert_notified=row['status_alert_notified'],
                ))
            return states

    def save(self, heartbeat, last_seen_at, stale_notified, status_alert_notified):
        """입력: heartbeat와 수신/알림 상태. 반환: 없음. 관리 테이블은 별도로 유지한다."""
        h = heartbeat
        with self.transaction() as conn:
            active = self.monitoring_allowed(h.device_id)
            if conn.execute('SELECT deleted FROM devices WHERE device_id=%s', (h.device_id,)).fetchone()['deleted']:
                return
            conn.execute('''INSERT INTO device_states
                (device_id,raw_payload,kafka_key,kafka_topic,kafka_partition,kafka_offset,
                 last_seen_at,stale_notified,status_alert_notified)
                VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s)
                ON CONFLICT(device_id) DO UPDATE SET raw_payload=excluded.raw_payload,
                kafka_key=excluded.kafka_key,kafka_topic=excluded.kafka_topic,
                kafka_partition=excluded.kafka_partition,kafka_offset=excluded.kafka_offset,
                last_seen_at=excluded.last_seen_at,stale_notified=excluded.stale_notified,
                status_alert_notified=excluded.status_alert_notified''',
                (h.device_id,h.raw_text,h.key,h.topic,h.partition,h.offset,last_seen_at,
                 stale_notified and active,status_alert_notified and active))

    def mark_stale(self, device_id):
        """입력: 장비 ID. 반환: 없음. 미수신 경고 등록을 기록한다."""
        with self.transaction() as conn:
            if self.monitoring_allowed(device_id):
                conn.execute('UPDATE device_states SET stale_notified=TRUE WHERE device_id=%s', (device_id,))

    def enqueue(self, heartbeat, notification_type, detail):
        """입력: heartbeat, 알림 종류와 설명. 반환: 신규 작업 등록 여부."""
        h = heartbeat
        key = f'{h.device_id}:{notification_type}'
        if notification_type != 'MISSING':
            key += f':{h.status_level}:{h.status_code}'
        with self.transaction() as conn:
            if not self.monitoring_allowed(h.device_id):
                return False
            result = conn.execute('''INSERT INTO notification_queue
                (dedupe_key,device_id,notification_type,detail,next_attempt_at,raw_payload,
                 kafka_key,kafka_topic,kafka_partition,kafka_offset)
                VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
                ON CONFLICT DO NOTHING RETURNING id''',
                (key,h.device_id,notification_type,detail,time.time(),h.raw_text,h.key,h.topic,h.partition,h.offset))
            return result.fetchone() is not None

    def mark_status_alert(self, device_id, notified):
        """입력: 장비 ID와 경고 등록 여부. 반환: 없음. 제외 중에는 등록 플래그를 지운다."""
        with self.transaction() as conn:
            active = self.monitoring_allowed(device_id)
            conn.execute('UPDATE device_states SET status_alert_notified=%s WHERE device_id=%s',
                         (bool(notified and active), device_id))

    def claim_next(self, now):
        """입력: 현재 epoch 초. 반환: 선점한 알림 또는 None. 동시 선점은 행 잠금으로 방지한다."""
        with self.transaction() as conn:
            row = conn.execute('''SELECT * FROM notification_queue
                WHERE status IN ('PENDING','RETRY') AND next_attempt_at<=%s
                ORDER BY id FOR UPDATE SKIP LOCKED LIMIT 1''', (now,)).fetchone()
            if row is None:
                return None
            conn.execute("UPDATE notification_queue SET status='SENDING',updated_at=now() WHERE id=%s", (row['id'],))
            return NotificationJob(row['id'],row['dedupe_key'],
                HeartbeatMessage.from_kafka_record(_StoredKafkaRecord(row)),
                row['notification_type'],row['detail'],row['attempt_count'])

    @contextmanager
    def delivery_guard(self, job):
        """입력: 발송 작업. 반환: 발송 허용 여부. 관리 API와 발송 직전 검사를 직렬화한다."""
        with self.transaction() as conn:
            self.lock_management(job.heartbeat.device_id)
            device = conn.execute('SELECT enabled,deleted FROM devices WHERE device_id=%s',
                                  (job.heartbeat.device_id,)).fetchone()
            active = device is not None and device['enabled'] and not device['deleted']
            row = conn.execute('SELECT status FROM notification_queue WHERE id=%s', (job.id,)).fetchone()
            allowed = active and row is not None and row['status'] == 'SENDING'
            if not allowed:
                conn.execute("UPDATE notification_queue SET status='CANCELLED',updated_at=now() "
                             "WHERE id=%s AND status='SENDING'", (job.id,))
            yield allowed

    def mark_sent(self, job_id):
        """입력: 작업 ID. 반환: 없음. SMTP 완료 상태를 기록한다."""
        with self.transaction() as conn:
            conn.execute("UPDATE notification_queue SET status='SENT',sent_at=now(),updated_at=now() "
                         "WHERE id=%s AND status='SENDING'", (job_id,))

    def mark_failed(self, job_id, error, next_attempt_at, dead):
        """입력: 실패 정보. 반환: 없음. 취소된 작업을 재시도로 되살리지 않는다."""
        with self.transaction() as conn:
            conn.execute('''UPDATE notification_queue SET status=%s,last_error=%s,
                next_attempt_at=%s,attempt_count=attempt_count+1,updated_at=now()
                WHERE id=%s AND status='SENDING' ''',
                ('DEAD' if dead else 'RETRY',error,next_attempt_at,job_id))

    def list_devices(self, limit=100, offset=0, include_deleted=False):
        """입력: 페이지와 삭제 포함 여부. 반환: 관리 및 최신 수신 상태 행 목록."""
        with self.transaction() as conn:
            return conn.execute('''SELECT d.*,s.last_seen_at,s.stale_notified,s.raw_payload
                FROM devices d LEFT JOIN device_states s USING(device_id)
                WHERE (%s OR NOT d.deleted) ORDER BY d.device_id LIMIT %s OFFSET %s''',
                (include_deleted,limit,offset)).fetchall()

    def get_device(self, device_id):
        """입력: 장비 ID. 반환: 상태 행 또는 None."""
        with self.transaction() as conn:
            return conn.execute('''SELECT d.*,s.last_seen_at,s.stale_notified,s.raw_payload
                FROM devices d LEFT JOIN device_states s USING(device_id) WHERE d.device_id=%s''',
                (device_id,)).fetchone()

    def manage(self, device_id, enabled, deleted, reason):
        """입력: 관리 설정. 반환: 변경 행. 미등록은 KeyError, 미발송 큐는 함께 취소한다."""
        with self.transaction() as conn:
            self.lock_management(device_id)
            row = conn.execute('SELECT * FROM devices WHERE device_id=%s FOR UPDATE', (device_id,)).fetchone()
            if row is None:
                raise KeyError(device_id)
            if row['enabled'] == enabled and row['deleted'] == deleted and row['reason'] == reason:
                return row
            conn.execute('UPDATE devices SET enabled=%s,deleted=%s,reason=%s,updated_at=now() WHERE device_id=%s',
                         (enabled,deleted,reason,device_id))
            if row['enabled'] != enabled or row['deleted'] != deleted:
                conn.execute("UPDATE notification_queue SET status='CANCELLED',updated_at=now() "
                             "WHERE device_id=%s AND status IN ('PENDING','RETRY','SENDING')", (device_id,))
                conn.execute('UPDATE device_states SET stale_notified=FALSE,status_alert_notified=FALSE WHERE device_id=%s',
                             (device_id,))
            return conn.execute('SELECT * FROM devices WHERE device_id=%s', (device_id,)).fetchone()

    def close(self):
        """입력: 없음. 반환: 없음. 접속은 각 작업 종료 시 자동 해제된다."""


if __name__ == '__main__':
    from dotenv import load_dotenv
    load_dotenv()
    PostgresRepository(os.environ['DATABASE_URL']).initialize()
