apiVersion: v1
kind: Secret
metadata:
  name: healthcheck-monitor-secret
type: Opaque
stringData:
  KAFKA_SASL_USERNAME: "replace-me"
  KAFKA_SASL_PASSWORD: "replace-me"
  SMTP_USERNAME: "sender@example.com"
  SMTP_PASSWORD: "replace-me"
