apiVersion: v1
kind: Secret
metadata:
  name: healthcheck-monitor-secret
type: Opaque
stringData:
  KAFKA_SASL_USERNAME: "replace-me"
  KAFKA_SASL_PASSWORD: "replace-me"
  ORACLE_USER: "replace-me"
  ORACLE_PASSWORD: "replace-me"
